### PR TITLE
Tuan student removal

### LINKED ISSUE #23: SUBISSUE: Remove ROLE_STUDENT from the code base (use ROLE_USER in place of it)
Previous sub issues asked you to make all users student by default, and remove the frontend and backend code for toggling ROLE_STUDENT.

In this issue, you'll remove the ROLE_STUDENT completely and just use "ROLE_USER" everywhere that ROLE_STUDENT was used.

### Summary

There are 3 roles in proj-rec: student, professor, and admin. All users can be students, but not all users can be admins/professors automatically. Thus, we should ensure that all users are designated as students when they first log in.

### Expected Behavior

When a user authenticates and logs in for the first time, they should automatically be given the `student` role.

### Current / Observed Behavior

Currently, when users join for the first time, they are not given any roles except `user` (and admin if they are part of admin emails).

### Steps to Reproduce

1. Navigate to the deployment of proj-rec, or run it locally
2. Click log in with a new email
3. If admin, click to see all users and you can see that the new user is not a student or professor by default.

Image

### PR DESCRIPTION
**Pull request by Leexe**
Closes #23 
Merge After #3 

I removed all instances of ROLE_STUDENT and allowed basic users to request recommendations. In other words, basic users have all the abilities that the student role use to have.

To Test:
1) Go to https://rec-leexe-dev.dokku-13.cs.ucsb.edu/
2) Log in to a non-ucsb account
3) Check the nav bar and you should be able to access the recommendation request tabs

Screenshot 2025-05-13 at 8 39 11 PM

### CODE REVIEW

**Review by timothytwu — DISMISSED** [review]
Looks good to me

File: src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java [hunk 1]
```diff
@@ -146,7 +146,7 @@ public RecommendationRequest updateRecommendationRequestAsAdmin(
     @GetMapping("/requester/all")
     public Iterable<RecommendationRequest> allRequesterRecommendationRequests(
     ) {
-        // toyed with having this only be ROLE_STUDENT but I think even professors should be able to submit requests so they can see which ones they have submitted too
+        // Professors should be able to submit requests so they can see which ones they have submitted to
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java]: I think in the end it's probably better to just remove this comment; I'm not sure it's helping anything at this point.  You can just click "commit suggestion" if you agree.

```suggestion
```

**Review by pconrad — DISMISSED** [review]
Code looks good to me apart from one comment that I think we may way to remove.

The description says:
>  I removed all instances of ROLE_STUDENT and allowed basic users to make recommendations

So, I think this may be mistaken: basic users should be allowed to **_request_** recommendations.

But only professors/instructors **_make_** recommendations.

There's no problem with the code; that looks fine.

But it's important to get the description correct as well; your team will rely on these descriptions later on when making the release notes and final video.

Can you consider updating this?

**Comment by Leexe** [comment]
@pconrad I have accepted your change to delete the unnecessary comment and reworded my description to be more correct.

**Review by pconrad — APPROVED** [review]
LGTM!
