### PR TITLE
Nikunj - Fix Admin Page Self-Toggle Bug

### LINKED ISSUE #43: SUBISSUE: Fix admin toggle backend bug
issue mentioned here: https://github.com/ucsb-cs156-s25/proj-rec-s25-13/pull/39#issuecomment-2888566674

### PR DESCRIPTION
**Pull request by nikunjparasar**
Closes #43 

This is a simple QoL fix for admin users using the admin page. In the chance that they click "toggle admin" on themselves, they remove access to api endpoints on that page, which causes API errors. 

I fixed this bug by implementing a custom backend error, and a handler to propagate the error to the frontend. 

To test: try toggling admin on yourself on localhost or [dokku](https://rec-nikunjparasar-dev.dokku-13.cs.ucsb.edu)

image

### CODE REVIEW

**Review by k-nn-tht — COMMENTED** [review]
I tested this out and I like the changes you made. I gave admin privilege to my alt acc and then signed into my alt and took off admin and it redirected to homepage. 

Though when it redirects to the homepage, it still has the admin dropdown in the navbar.

It goes away with a refresh or switching tabs but just wanted to comment on it to see if it is possible to fix?

**Comment by pconrad** [comment]
> I tested this out and I like the changes you made. I gave admin privilege to my alt acc and then signed into my alt and took off admin and it redirected to homepage.
> 
> Though when it redirects to the homepage, it still has the admin dropdown in the navbar.
> 
> It goes away with a refresh or switching tabs but just wanted to comment on it to see if it is possible to fix?

I wonder if it would just be easier to prevent users from removing themselves as admins?

That is, in the toggle admin, see if the user being toggled is equal to currentUser, and if so, just do

```
throw new IllegalArgumentException("Cannot remove admin from currently logged in user; ask another admin to do that.");
```

As long as the frontend is set up to handle the error, the error message will propagate to the frontend.  I'll link to an example of how to set that up.

**Comment by pconrad** [comment]
> > I tested this out and I like the changes you made. I gave admin privilege to my alt acc and then signed into my alt and took off admin and it redirected to homepage.
> > Though when it redirects to the homepage, it still has the admin dropdown in the navbar.
> > It goes away with a refresh or switching tabs but just wanted to comment on it to see if it is possible to fix?
> 
> I wonder if it would just be easier to prevent users from removing themselves as admins?
> 
> That is, in the toggle admin, see if the user being toggled is equal to currentUser, and if so, just do
> 
> ```
> throw new IllegalArgumentException("Cannot remove admin from currently logged in user; ask another admin to do that.");
> ```
> 
> As long as the frontend is set up to handle the error, the error message will propagate to the frontend. I'll link to an example of how to set that up.

To get errors messages in exceptions thrown in controllers to propagate to the frontend, do this:

(1) Throw exception in the controller.  Pass the error message you want the user to see as a parameter to the exception.

e.g.

```java
throw new IllegalArgumentException("Cannot remove admin from currently logged in user; ask another admin to do that.");
```

(2) Make sure that the `ApiController` has an error handler for the type of exception you threw, e.g. 

https://github.com/ucsb-cs156/proj-courses/blob/ebaff85a99f71f8162cb41da17b0f5ff75d2c0d7/src/main/java/edu/ucsb/cs156/courses/controllers/ApiController.java#L35

```java
  @ExceptionHandler({IllegalArgumentException.class})
  @ResponseStatus(HttpStatus.BAD_REQUEST)
  public Object handleIllegalArgumentException(Throwable e) {
    return Map.of(
        "type", e.getClass().getSimpleName(),
        "message", e.getMessage());
  }
```

(3) In the frontend, be sure that you  pass an `onError` error handler to the `backendMutation` call like this:

https://github.com/ucsb-cs156/proj-courses/blob/ebaff85a99f71f8162cb41da17b0f5ff75d2c0d7/frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js#L24

```javascript
  const mutation = useBackendMutation(
    objectToAxiosParams,
    { onSuccess, onError },
    // Stryker disable next-line all : hard to set up test for caching
    ["/api/personalschedules/all"],
  );
```

(4) Write the `onError` function to get the message and show it to the user in a toast: 

https://github.com/ucsb-cs156/proj-courses/blob/ebaff85a99f71f8162cb41da17b0f5ff75d2c0d7/frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js#L20C1-L22C5

```javascript
  const onError = (error) => {
    toast(`Error: ${error.response.data.message}`);
  };
```

**Review by chengcxi — DISMISSED** [review]
Was NOT able to remove admin from myself after logging in on dokku.

File: frontend/src/main/components/Users/UsersTable.js [hunk 1]
```diff
@@ -1,10 +1,15 @@
 import OurTable, { ButtonColumn } from "main/components/OurTable";
 import { useBackendMutation } from "main/utils/useBackend";
+import { toast } from "react-toastify";
+import axios from "axios";
+import { useMutation, useQueryClient } from "react-query";
 
 export default function UsersTable({ users }) {
   // Stryker disable all : hard to test for query caching
   // Stryker enable all
```
Comment (pconrad) [inline frontend/src/main/components/Users/UsersTable.js]: It appears that this team removed the code here, but did not remove the stryker lines.

Since you are in this file anyway, can you clean this up by removing both of these lines?

(This was in #27 )

image

File: frontend/src/main/components/Users/UsersTable.js [hunk 2]
```diff
@@ -16,13 +21,33 @@ export default function UsersTable({ users }) {
...
+        }
+        throw error; // Re-throw to maintain error state in mutation
+      }
+    },
+    {
+      onSettled: () => {
+        queryClient.invalidateQueries(["/api/admin/users"]);
+      },
+      retry: false,
+    },
```
Comment (pconrad) [inline frontend/src/main/components/Users/UsersTable.js:46]: I won't necessarily make you change this, but I'll point out that there is an easier way:

See: https://ucsb-cs156.github.io/topics/spring_react/spring_react_propagating_errors.html

**Review by pconrad — CHANGES_REQUESTED** [review]
One small clean up change to request, then this is good to go.

**Review by pconrad — APPROVED** [review]
LGTM
